import './globals.css'
import { Inter } from 'next/font/google'
import { Nunito } from 'next/font/google'
import Navbar from './components/Navbar'
import Footer from './components/Footer'

const inter = Inter({ subsets: ['latin'] })


const nunito = Nunito ({ subsets: ['latin'] })

export const metadata = {
  title: 'UVISE',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={nunito.className} >
      
        <header>
          <Navbar/>
          </header>
        <main>
          {children}
        </main>
       <Footer/>
          </body>
    </html>
  )
}
